name: Build - CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: xaviersolau/devops-workflows/.github/workflows/build-dotnet.yml@v1.3.0
    with:
      run-pack: true
      pack-folders: >
        [
          "src/libs",
          "src/tools"
        ]
      test-projects: >
        [
          "src/tests/SoloX.BlazorJsonLocalization.UTests",
          "src/tests/SoloX.BlazorJsonLocalization.ServerSide.UTests",
          "src/tests/SoloX.BlazorJsonLocalization.ITests",
          "src/tools.tests/SoloX.BlazorJsonLocalization.Tools.Core.UTests",
          "src/tools.tests/SoloX.BlazorJsonLocalization.Tools.Core.ITests",
          "src/tools.tests/SoloX.BlazorJsonLocalization.Tools.Command.ITests",
          "src/tools.tests/SoloX.BlazorJsonLocalization.Generator.ITests"
        ]